### ISSUE TITLE
モバイル版のテンプレート選択機能の閉じるボタンは固定で見える場所にいて欲しい

### ISSUE THREAD

**Issue by ics-nohara** [ics-creative/project-particle-develop#3]
選択してから、最下部までスクロールしないと閉じることができないため。

**Comment by ics-ikeda** [comment]
上下にボタンを追加し、UIを改善したのでクローズします。

![ics-creative github io_project-particle-develop_ iphone 6_7_8](https://user-images.githubusercontent.com/975273/40770548-f623264e-64f5-11e8-9d58-e548ed572868.png)
